Skip to content
Search or jump to…

Pull requests
Issues
Marketplace
Explore
 
@Pavani123429 
Pavani123429
/
RAILWAY-RESERVATION-SYSTEM
1
00
Code
Issues
1
Pull requests
Actions
Projects
Wiki
Security
Insights
Settings
RAILWAY-RESERVATION-SYSTEM
/
.github
/
workflows
/
dynamic-code-quality.yml
in
main
 

Spaces

2

No wrap
1
name: C/C++ CI
2
​
3
on:
4
  push:
5
    branches: [ main ]
6
  pull_request:
7
    branches: [ main ]
8
​
9
jobs:
10
  build:
11
​
12
    runs-on: ubuntu-latest
13
​
14
    steps:
15
    - uses: actions/checkout@v2
16
    - name: configure
17
      run: ./configure
18
    - name: make
19
      run: make
20
    - name: make check
21
      run: make check
22
    - name: make distcheck
23
      run: make distcheck
24
​
Use Control + Space to trigger autocomplete in most situations.
Search Marketplace for Actions
Featured Actions

Cache artifacts like dependencies and build outputs to improve workflow execution time

 1.9k

Setup a Node.js environment by adding problem matchers and optionally downloading and adding it to the PATH

 1k

Close issues and pull requests with no recent activity

 365

Download a build artifact that was previously uploaded in the workflow by the upload-artifact action

 292

Greet new contributors when they create their first issue or open their first pull request

 90
Featured categories
Browse all actions on the GitHub Marketplace
